All feature
WildCodeSchool-2024-02/LILLE-0224-P3-G1-babyplace pull request #13
Opened 2024-06-18 14:47 UTC by PMorganGit

2024-06-18 15:14 UTC, EmilieLgt approved these changes

2024-06-19 07:16 UTC, fantinerudent requested changes

2024-06-19 07:16 UTC, fantinerudent commented on client/public/assets/images/2_structure2.png
y'a plein de fautes d'orthographe...

2024-06-19 07:16 UTC, fantinerudent commented on client/src/components/Bottom_navbar/BottomNavbar.jsx
> +  const [dashboardeButton, setDashboardButton] = useState(false);
dashbord*

2024-06-19 07:16 UTC, fantinerudent commented on client/src/components/NurseriesPlateform/NurseriesMini.jsx
> +/* eslint-disable react/prop-types */
no no no...

2024-06-19 07:16 UTC, fantinerudent commented on client/src/components/NurseriesPlateform/NuseriesMap.jsx
> +/* eslint-disable react/prop-types */
nop

2024-06-19 09:50 UTC, fantinerudent approved these changes

2024-06-19 09:51 UTC, merged