login parent & pro responsive + path
WildCodeSchool-2024-02/LILLE-0224-P3-G1-babyplace pull request #15
Opened 2024-06-19 14:40 UTC by PMorganGit

2024-06-19 14:45 UTC, saile117 approved these changes
c'est génial

2024-06-19 14:54 UTC, fantinerudent requested changes

2024-06-19 14:54 UTC, fantinerudent commented on client/src/components/LoginPro/LoginPro.jsx
> +  const [accountButton, setaccountButton] = useState(true);
camel case, setAccount*

2024-06-19 14:54 UTC, fantinerudent commented on client/src/components/LoginPro/LoginPro.jsx
> +  const handleaccountButton = () => {
same

2024-06-20 13:04 UTC, fantinerudent approved these changes

2024-06-20 13:07 UTC, merged