Data base repositories
WildCodeSchool-2024-02/LILLE-0224-P3-G1-babyplace pull request #21
Opened 2024-06-20 14:26 UTC by BENOITMEZAGUER

2024-06-20 14:50 UTC, EmilieLgt commented on server/database/fixtures/ParentSeeder.js
> +        refName: `parent_${parent.parent_lastname}`,
mail plutot que lastname pour que ça soit unique ?

2024-06-21 09:43 UTC, fantinerudent requested changes
je pense qu'il serait plus propre de supprimer tous les commentaires parce qu'ils sont répétés dans CHAQUE fichier

2024-06-21 09:45 UTC, EmilieLgt approved these changes

2024-06-21 12:08 UTC, saile117 approved these changes

2024-06-21 13:31 UTC, merged