dashboard for admin dekstop + path
WildCodeSchool-2024-02/LILLE-0224-P3-G1-babyplace pull request #23
Opened 2024-06-20 15:12 UTC by PMorganGit

2024-06-21 08:28 UTC, saile117 approved these changes

2024-06-24 08:40 UTC, fantinerudent requested changes

2024-06-24 08:40 UTC, fantinerudent commented on client/src/pages/Dashboard/PageAdminDashboard.jsx
> +    <div>
pas d'utilité d'avoir autant de div container

2024-06-26 09:17 UTC, fantinerudent approved these changes

2024-06-26 10:21 UTC, merged