Seeders
WildCodeSchool-2024-02/LILLE-0224-P3-G1-babyplace pull request #40
Opened 2024-07-02 09:09 UTC by BENOITMEZAGUER

2024-07-02 09:42 UTC, fantinerudent approved these changes

2024-07-02 09:42 UTC, fantinerudent commented on server/app/controllers/authentificationActions.js
> +  // je vais recuperer le body de la requete d'authentification
commentaire en français / les autres sont en anglais

2024-07-02 09:42 UTC, fantinerudent commented on server/app/controllers/parentActions.js
> +      //   { nom: "toto", prenom: "richard", email: "toto@richard.com", mdp: "jaimeleketchupdu59"...}
delete héhé

2024-07-02 09:42 UTC, fantinerudent commented on server/app/controllers/parentActions.js
> +// todo creer une nouvelle fonction get by email
delete

2024-07-02 09:42 UTC, fantinerudent commented on server/app/routers/api/parent/router.js
> +// ajouter les middleware dans tous les login pour verifier le mdp.
delete

2024-07-02 09:42 UTC, fantinerudent requested changes
see comments

2024-07-02 09:49 UTC, BENOITMEZAGUER reviewed
done with the changes

2024-07-02 10:23 UTC, EmilieLgt approved these changes

2024-07-08 14:17 UTC, fantinerudent approved these changes

2024-07-08 14:17 UTC, fantinerudent commented on server/database/fixtures/ParentSeeder.js
> +        parent_password: "azerty2",
tu vas avoir des difficultés si le password est pas hashed

2024-07-08 14:18 UTC, merged