cookies done
WildCodeSchool-2024-02/LILLE-0224-P3-G1-babyplace pull request #49
Opened 2024-07-11 13:00 UTC by BENOITMEZAGUER

2024-07-11 14:09 UTC, PMorganGit approved these changes

2024-07-11 15:03 UTC, fantinerudent requested changes

2024-07-11 15:03 UTC, fantinerudent commented on server/app/controllers/authentificationActions.js
> +  // Je vais récupérer le body de la requête d'authentification
du coup mettre le commentaire en anglais aussi

2024-07-11 15:03 UTC, fantinerudent commented on server/app/controllers/authentificationActions.js
> +      // psw: info.parent_password,
dead code

2024-07-11 15:10 UTC, BENOITMEZAGUER reviewed
done

2024-07-12 07:45 UTC, fantinerudent requested changes

2024-07-12 07:45 UTC, fantinerudent commented on server/app/controllers/authentificationActions.js
> +      // user: info,
dead code.......

2024-07-12 08:13 UTC, BENOITMEZAGUER reviewed
dead code removed

2024-07-12 14:29 UTC, fantinerudent approved these changes

2024-07-12 14:36 UTC, merged